(* ::Package:: *)

(* ::Input:: *)
(*(*Euler Methods for Parital Derivation Equation*)*)
(*ClearAll["Global`"];*)
(*Clear[y]*)
(*BoundaryLeft = 0;*)
(*BoundaryRight = 1;*)
(*ValueLeft = 0;*)
(*ValueRight  = 0;*)
(*SplitNum=5;*)
(*F[deltax_,x_]:=z'[x]^2+z[x]^2+2deltax z[x]*)
(*(*Delta x*)*)
(*gap = (BoundaryRight-BoundaryLeft)/SplitNum;*)
(*SplitPointList = Table[i,{i,BoundaryLeft,BoundaryRight,gap}]*)
(*(*yform[x_]:=Table[(SplitPointList[[i]]-x)/(SplitPointList[[i]]-SplitPointList[[i-1]])*y[i-2]+*)
(*(x-SplitPointList[[i-1]])/(SplitPointList[[i]]-SplitPointList[[i-1]])*y[i-1],{i,2,SplitNum+1}]*)*)
(*(*Boundary Condition*)*)
(*y[0]:=ValueLeft;*)
(*y[SplitNum]:=ValueRight;*)
(*z'[x_Integer]:=(y[x]-y[x-1])/gap;*)
(*z[x_Integer]:=y[x];*)
(*(*Integrator Approximation*)*)
(*phi =Sum[F[SplitPointList[[x+1]],x],{x,1,SplitNum}];*)
(*(*Equal to zeros after derivation*)*)
(*Table[D[phi,y[i]]==0,Table[y[i],{i,1,SplitNum-1}]]*)
(*N[Solve[Table[D[phi,y[i]]==0,{i,1,SplitNum-1}],Table[y[i],{i,1,SplitNum-1}]]]*)
(*phi*)



